In [5]:
import pandas as pd
import numpy as np

In [12]:
data = pd.read_csv("cellpose_segmentation/transcripts.csv")

In [13]:
data

,Unnamed: 0.1,Unnamed: 0,barcode_id,global_x,global_y,global_z,x,y,fov,gene,transcript_id,mask
0,0,329140,96,3822.6140,134.603240,4.0,206.57428,1246.32630,0,Pycr1,ENSMUST00000026133,0
1,1,425522,128,3865.5085,89.455734,5.0,603.74640,828.29380,0,Slc7a11,ENSMUST00000029297,0
2,2,810570,241,3972.9065,163.452200,6.0,1598.17210,1513.44620,0,Cxcr3,ENSMUST00000056614,0
3,3,1294999,381,3968.8958,33.911680,0.0,1561.03550,313.99704,0,Ldhb,ENSMUST00000130817,0
4,4,1844539,536,3814.5425,132.516770,0.0,131.83746,1227.00710,0,Blank-42,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
16296383,16296383,891678,260,2750.3667,7003.081500,0.0,1390.35860,1875.34850,856,Ppp6r1,ENSMUST00000064099,0
16296384,16296384,1096165,316,2643.0085,6867.693000,1.0,396.30136,621.74725,856,Icos,ENSMUST00000102827,0
16296385,16296385,1337621,386,2659.0680,6997.968000,2.0,545.00000,1828.00000,856,Itga2b,ENSMUST00000103086,0
16296386,16296386,1622514,477,2635.3728,6870.979500,0.0,325.60034,652.18134,856,Hmgcs1,ENSMUST00000224188,0
16296387,16296387,1622590,477,2810.0360,6958.539600,0.0,1942.84960,1462.92320,856,Hmgcs1,ENSMUST00000224188,0

In [16]:
data_subset = data[
    (data.global_x > 2200) &  (data.global_x < 3800) &
    (data.global_y > 2200) &  (data.global_y < 3800)
]

In [17]:
data_subset

,Unnamed: 0.1,Unnamed: 0,barcode_id,global_x,global_y,global_z,x,y,fov,gene,transcript_id,mask
4332881,4332881,1231,1,3627.1620,2200.0050,0.0,248.83401,1850.4149,217,Klf6,ENSMUST00000000080,0
4332889,4332889,1692,1,3612.0935,2206.9036,1.0,109.30848,1914.2911,217,Klf6,ENSMUST00000000080,26411
4332890,4332890,1695,1,3622.2990,2208.7095,1.0,203.80570,1931.0138,217,Klf6,ENSMUST00000000080,26376
4332891,4332891,1696,1,3621.5176,2208.9019,1.0,196.56944,1932.7949,217,Klf6,ENSMUST00000000080,0
4332917,4332917,2630,1,3711.0870,2200.0193,3.0,1025.91580,1850.5490,217,Klf6,ENSMUST00000000080,26354
...,...,...,...,...,...,...,...,...,...,...,...,...
9025483,9025483,1762436,487,2208.8777,3758.8025,0.0,1932.57080,1467.7257,474,Epcam,ENSMUST00000234623,0
9025484,9025484,1762440,487,2208.6510,3759.7375,0.0,1930.47000,1476.3840,474,Epcam,ENSMUST00000234623,0
9025814,9025814,1764102,487,2208.4558,3757.2253,1.0,1928.66460,1453.1232,474,Epcam,ENSMUST00000234623,0
9026176,9026176,1765882,487,2208.8723,3758.6426,2.0,1932.52110,1466.2444,474,Epcam,ENSMUST00000234623,0
9026177,9026177,1765885,487,2209.2214,3759.6100,2.0,1935.75270,1475.2032,474,Epcam,ENSMUST00000234623,0

In [18]:
data_subset.to_csv("cellpose_segmentation/transcripts_subset.csv")